### ISSUE TITLE
0.2.0+mc1.21.0 crash

### ISSUE THREAD

**Issue by Pumpk1in** [ToBinio/better-snow-coverage#5]
Hi, I just updated your mod and now it crashes while loading the map. (Solo or multi)
I was fine before the sodium update that broke your mod rendering.

`java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_31548()" because "this.field_3712.field_1724" is null
at net.minecraft.class_636.method_2911(class_636.java:302)
at net.minecraft.class_636.method_2927(class_636.java:285)
at net.minecraft.class_310.method_1574(class_310.java:1908)
at net.minecraft.class_310.method_1523(class_310.java:1246)
at net.minecraft.class_310.method_1514(class_310.java:882)
at net.minecraft.client.main.Main.main(Main.java:256)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)`

Do I need something else ?
I'm using iris.

**Comment by ToBinio** [comment]
are you using sodium 0.6?
sodium 0.5 won't work anymore

**Comment by Pumpk1in** [comment]
Yes I'm using 0.6.0-beta.1 for Fabric

**Comment by ToBinio** [comment]
i quickly tested it my self, it seems to be kinda related to iris, but the crash does still happen even without iris.
will investigate tomorrow

**Comment by ToBinio** [comment]
small note: I have taken down the version since it seems to be completely broken... 
Thanks for reporting!

**Comment by ToBinio** [comment]
so i just reuploaded [0.2](https://modrinth.com/mod/better-snow-coverage/version/0.2.0+mc1.21.0)
this should now work

please let me know if it does not

**Comment by Pumpk1in** [comment]
Perfectly fine to me ✨
Thank you !

**Comment by ToBinio** [comment]
nice to hear!
thanks for reporting!
